### PR TITLE
Allow overriding stagingRelease

### PR DESCRIPTION
**Pull request by nightscape**
This allows using the plugin for the open-source version of Nexus (which does not support staging) as well, e.g. internal Nexus repos.

### CODE REVIEW

**Comment by nightscape** [comment]
Hi @ckipp01, I fixed the formatting issue and put a section into the README.
Good to go from my side 😃

**Review by ckipp01 — APPROVED** [review]
Looks good, LGTM!

Thanks @nightscape!

**Comment by ckipp01** [comment]
So this merge created `0.1.5-19-f53626-SNAPSHOT`. Can you give that a shot @nightscape and double-check that it all works as expected? If so, I can go ahead and cut a new release.

**Comment by nightscape** [comment]
@ckipp01 unfortunately the project in which I used this has ended last Friday and I don't have access to that Nexus instance anymore.
But I had successfully used my (JitPack'ed) version of the code while I was on the project.

**Pull request merged**
